apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: vanshikaverma11/sn-labsapp:v2.0  # Replace <your_image> with the actual image for your app
        ports:
        - containerPort: 3000
